---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.31.1"
    file:
      - "defaults/stages.yaml"
      - "defaults/nubus-workflow.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build.yaml"

variables:
  TEST_PORTAL_BASE_URL:
    description: "The base URL of the portal to test. Example: https://portal.uv-username.gaia.open-desk.cloud/univention/portal/"

.build-matrix: &build-matrix
  - IMAGE_NAME:
      - "e2e-tests-runner"
    KANIKO_BUILD_CONTEXT: $CI_PROJECT_DIR
    DOCKERFILE_PATH: "Dockerfile"

container-build:
  parallel:
    matrix: *build-matrix


e2e-tests:
  stage: "test"
  image: "$CI_REGISTRY_IMAGE/e2e-tests-runner:${RELEASE_VERSION}"
  artifacts:
    expose_as: "report"
    paths:
      - "${CI_PROJECT_DIR}/report.html"
      - "${CI_PROJECT_DIR}/test-results/"
    when: "always"
    reports:
      junit: "test_results.xml"
    expire_in: "14 days"
  variables:
    PORTAL_BASE_URL: "${TEST_PORTAL_BASE_URL}"
  script: |
    ./entrypoint.sh pytest --showlocals --junitxml=test_results.xml --html=report.html --self-contained-html --capture=no --verbose
  tags:
    - "docker"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "api"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
