[project]
name = "pages"
version = "0.2.0"
description = "Page Objects used for end to end testing in the SouvAP Dev team"
maintainers = [
    {name = "Univention GmbH", email = "packages@univention.de"},
]
license = {text = "GNU Affero General Public License v3"}
readme = "README.md"
requires-python = ">=3.8,<4"
dependencies = [ "playwright==1.30.0" ]

[project.optional-dependencies]
tests = [ "pytest-playwright==0.3.0", "requests==2.31.0", "url-normalize==1.4.3", "pytest-html==4.0.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/pages"]

[tool.pytest.ini_options]
pythonpath = [ "src" ]
testpaths = [ "tests" ]
markers = [ "saml: all tests that enforce SAML login. Other tests may also use SAML depending on the environment" ]
